{{ if (not .Values.customResourceDefinitions.skip) }}
# The CRD for Howso Enterprise Job Runners
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: job-runners.howso.com
  annotations:
    "helm.sh/resource-policy": keep
spec:
  scope: Namespaced
  group: howso.com
  names:
    kind: JobRunner
    plural: job-runners
    singular: job-runner
    shortNames:
      - job-runners
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Job Type
          type: string
          jsonPath: .spec.job_type
          description: Type type of job
        - name: Run Type
          type: string
          jsonPath: .spec.job_run_type
          description: The type of run for the job
        - name: State
          type: string
          jsonPath: .status.state
          description: Phase of underlying job runner resource
        - name: Desired State
          type: string
          jsonPath: .status.desired_state
          description: Desired state of underlying job runner resource
        - name: Age
          jsonPath: .metadata.creationTimestamp
          description: The age of this resource
          type: date
{{ end }}
