{{ if .Values.imageLoader.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: platform-imageloader
  labels:
    app.kubernetes.io/part-of: howso-platform
    app.kubernetes.io/component: image-loader
    name: image-loader
spec:
  selector:
    matchLabels:
      name: image-loader
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: howso-platform
        app.kubernetes.io/component: image-loader
        name: image-loader
      annotations: 
      {{- toYaml .Values.imageLoader.podAnnotations | nindent 8 }} 
    spec:
      {{- with .Values.images.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.imageLoader.podSecurityContext | nindent 8 }} 
      initContainers:
        - name: trainee-image-loader
          image: {{ include "howso-platform.imagePath" (dict "root" $ "image" .Values.worker.image) | quote }}
          imagePullPolicy: Always
          securityContext:
            {{- toYaml .Values.imageLoader.securityContext | nindent 12 }}
          command: ['sh', '-c', "echo image: {{ .Values.worker.image.name }}:{{ .Values.worker.image.tag }} loaded"]
          resources:
            {{- toYaml .Values.imageLoader.resources | nindent 12 }}
        {{- if .Values.jobRunner.enabled }} 
        - name: job-runner-image-loader
          image: {{ include "howso-platform.imagePath" (dict "root" $ "image" .Values.jobRunner.image) | quote }}
          imagePullPolicy: Always
          securityContext:
            {{- toYaml .Values.imageLoader.securityContext | nindent 12 }}
          command: ['sh', '-c', "echo image: {{ .Values.jobRunner.image.name }}:{{ .Values.jobRunner.image.tag }} loaded"]
          resources:
            {{- toYaml .Values.imageLoader.resources | nindent 12 }}
        {{- end }}
      containers:
        - name: pause
          image: '{{ .Values.imageLoader.pauseImage}}'
          imagePullPolicy: Always
          securityContext:
            {{- toYaml .Values.imageLoader.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.imageLoader.resources | nindent 12 }}
      tolerations:
        {{- toYaml .Values.tolerations.workers | nindent 8 }}
      automountServiceAccountToken: false
{{ end }}
