---
{{ if .Values.networkPolicies.egress.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: platform-worker-egress-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: trainee-worker 
  policyTypes:
  - Egress
  egress: 
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: nats
          app.kubernetes.io/instance: platform-nats
    ports:
    - protocol: TCP
      port: 4222 
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: redis
          app.kubernetes.io/instance: platform-redis
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: object-store 
    ports:
    - protocol: TCP
      port: 9000 
  # This is to allow kubernetes api access
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 6443
{{ end }}