apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-worker-serviceaccount 
  labels:
    app.kubernetes.io/name: howso-platform 

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: platform-worker-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]

# NOTE: This is required to allow calling `patch_namespaced_custom_object`
#       used by `howso_platform_worker.model_operators.set_idle()`.
- apiGroups: ["{{ .Values.customResourceDefinitions.trainee.group }}"]
  resources: ["{{ .Values.customResourceDefinitions.trainee.plural }}"]
  verbs: [patch, ]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: platform-worker-rolebinding 
subjects:
- kind: ServiceAccount
  name: platform-worker-serviceaccount 
roleRef:
  kind: Role
  name: platform-worker-role 
  apiGroup: rbac.authorization.k8s.io
