{{ if .Values.pypi.security.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: platform-pypi-api-token-secret
type: Opaque
data:
  pypi_token: {{ .Values.pypi.security.token | b64enc }}
{{ end }}