{{ if .Values.networkPolicies.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: platform-pypi-ingress-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: platform-pypi 
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 8443
    - protocol: TCP
      port: 8080
{{ end }}
