apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true # This is required by the kubernetes client
metadata:
  name: platform-api-serviceaccount
  labels:
    {{- include "howso-platform.api.labels" . | nindent 4 }}
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: platform-api-role
rules:
  - apiGroups: ["howso.com"]
    resources: ["job-runners"]
    verbs: [get, list, watch, patch, create, delete]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: platform-api-rolebinding
subjects:
- kind: ServiceAccount
  name: platform-api-serviceaccount
roleRef:
  kind: Role
  name: platform-api-role
  apiGroup: rbac.authorization.k8s.io
