{{- if not (.Values.datastores.postgres.ums.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: platform-postgres-ums-credentials 
  labels:
    app: platform-postgres 
type: Opaque
data:
  password: "{{ .Values.datastores.postgres.ums.password | b64enc }}"
{{- end}}
---
{{- if not (.Values.datastores.postgres.platform.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: platform-postgres-platform-credentials 
  labels:
    app: platform-postgres 
type: Opaque
data:
  password: "{{ .Values.datastores.postgres.platform.password | b64enc }}"
{{- end}}