{{ if .Values.ums.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: platform-ums-django-secret
  {{- with .Values.ums.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
type: Opaque
data:
  secret: {{ randAlphaNum 60 | b64enc | quote }} # Randomly generated secret for Django 
{{- end }}
