{{- if .Values.podTLS.enabled }}
{{- if .Values.ums.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-ums-server-tls 
spec:
  secretName: platform-ums-server-tls 
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - Howso Platform
  commonName: platform-ums.default.svc.cluster.local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  usages:
    - server auth
  dnsNames:
  - platform-ums 
  issuerRef:
    name: {{ .Values.internalPKI.rootCASecretName }} 
    kind: Issuer
{{- end }}
{{- end }}