{{ if .Values.ums.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-ums-tls-sidecar-nginx-config
data:
  nginx.conf: {{ .Files.Get "files/ums.tls.nginx.conf" | indent 4 | quote }}
{{ end }}