{{ if .Values.ums.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: platform-ui-application-secret
type: Opaque
data:
  client_id: {{ "platform-ui-app-client-id" | b64enc | quote }} 
  client_secret: {{ randAlphaNum 130 | b64enc }} # Randomly generated secret 

{{ end }}
