{{ if .Values.ums.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: platform-ums-system-account-secret
type: Opaque
data:
  username: {{ "dp-system-ums" | b64enc | quote }} 
  client_id: {{ "dp-system-ums-client-id" | b64enc | quote }} 
  client_secret: {{ randAlphaNum 130 | b64enc }} # Randomly generated secret 
{{ end }}