{{ if .Values.notsvc.enabled }}
{{ if .Values.nats.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-notsvc-nats-client-tls 
spec:
  secretName: platform-notsvc-nats-client-tls 
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - Howso Platform
  commonName: platform-notsvc.default.svc.cluster.local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  usages:
    - client auth
  dnsNames:
  - platform-notsvc 
  issuerRef:
    name: {{ .Values.internalPKI.rootCASecretName }}
    kind: Issuer
{{ end }}
{{ end }}