{{ if .Values.networkPolicies.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: platform-notsvc-ingress-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: notification-service 
  policyTypes:
  - Ingress 
  ingress: [] 
{{ end }}
---
{{ if .Values.networkPolicies.egress.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: platform-notsvc-egress-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: notification-service 
  policyTypes:
  - Egress
  egress: 
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: nats
          app.kubernetes.io/instance: platform-nats
    ports:
    - protocol: TCP
      port: 4222 
{{ end }}