apiVersion: v1
kind: Secret
metadata:
  name: platform-notification-service-system-account-secret
type: Opaque
data:
  username: {{ "dp-system-ns" | b64enc | quote }} 
  client_id: {{ "dp-system-ns-client-id" | b64enc | quote }} 
  client_secret: {{ randAlphaNum 130 | b64enc }} # Randomly generated secret 
