apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true # This is required by the kubernetes client
metadata:
  name: platform-operator-serviceaccount
  labels:
    {{- include "howso-platform.operator.labels" . | nindent 4 }}


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: platform-kopf-role-namespaced
rules:

 # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the trainee resource
  # finalizers is specifically required by OpenShift
  - apiGroups: ["{{ .Values.customResourceDefinitions.trainee.group }}"]
    resources: ["{{ .Values.customResourceDefinitions.trainee.plural }}", "{{ .Values.customResourceDefinitions.trainee.plural }}/finalizers"]
    verbs: ["list", "watch", "patch", "create", "delete", "update"]

  - apiGroups: ["howso.com"]
    resources: ["job-runners", "job-runners/finalizers"]
    verbs: ["list", "watch", "patch", "create", "delete", "update"]

  - apiGroups: [apps]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]

  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get"]

  # NOTE: This is required to allow calling `read_namespaced_stateful_set_status`
  #       used by `platform_sms.model_operators.is_trainee_up`.
  - apiGroups: ["apps"]
    resources: ["statefulsets/status"]
    verbs: ["get" ]



---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-kopf-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: platform-kopf-role-namespaced
subjects:
  - kind: ServiceAccount
    name:  platform-operator-serviceaccount
---
