{{ if .Values.networkPolicies.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: platform-ui-v2-ingress-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: platform-ui2
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 8443
    - protocol: TCP
      port: 8000
    - protocol: TCP
      port: 8080
{{ end }}
---
{{ if .Values.networkPolicies.egress.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: platform-ui-v2-egress-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: notification-service
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: object-store
    ports:
    - protocol: TCP
      port: 9000

{{ end }}