{{ if .Values.ui2.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
  {{ if .Values.podTLS.enabled }}
    projectcontour.io/upstream-protocol.tls: 8443,https  # https://projectcontour.io/docs/main/config/upstream-tls/
  {{ end }}
  name: {{ include "howso-platform.ui2.fullname" . }}
  labels:
    {{- include "howso-platform.ui2.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{ if .Values.podTLS.enabled }}
    - port: 8443
      targetPort: https
      protocol: TCP
      name: https
    {{ else }}
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    {{ end }}
  selector:
    {{- include "howso-platform.ui2.selectorLabels" . | nindent 4 }}
{{ end }}