{{ if .Values.sms.clusterResourcesAPI.enabled }}
# Add this section for the ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-sms-node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["get", "list", "watch"]
---
# Add this section for the ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-sms-node-reader-binding
subjects:
  - kind: ServiceAccount
    name: platform-sms-serviceaccount
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: platform-sms-node-reader
  apiGroup: rbac.authorization.k8s.io
{{ end }}