apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true # This is required by the kubernetes client 
metadata:
  name: platform-sms-serviceaccount 
  labels:
    {{- include "howso-platform.sms.labels" . | nindent 4 }}
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: platform-sms-role
rules:
# Application: Getting metrics for trainee pods 
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: [list, get]

# Used for internal test endpoints - do not delete
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]

# NOTE: This is required to get the live pod status in the function
#       `platform_sms.model_operator.get_live_phase`
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["get"]

- apiGroups: ["{{ .Values.customResourceDefinitions.trainee.group }}"]
  resources: ["{{ .Values.customResourceDefinitions.trainee.plural }}"]
  verbs: [get, list, watch, patch, create, delete]


---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: platform-sms-rolebinding 
subjects:
- kind: ServiceAccount
  name:  platform-sms-serviceaccount 
roleRef:
  kind: Role
  name: platform-sms-role 
  apiGroup: rbac.authorization.k8s.io
---