apiVersion: v1
kind: Secret
metadata:
  name: platform-sms-system-account-secret
type: Opaque
data:
  username: {{ "dp-system-sms" | b64enc | quote }} 
  client_id: {{ "dp-system-sms-client-id" | b64enc | quote }} 
  client_secret: {{ randAlphaNum 130 | b64enc }} # Randomly generated secret 
