{{- if and .Values.global .Values.global.replicated .Values.global.replicated.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: platform-registry 
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.replicated.dockerconfigjson }}
{{- end }}
