apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-configmap-job-runner-conf
data:
  # Since the job runner is created dynamically - it is simpler to have these value in a configmap,
  # and read directly - rather than pass it in via the operator, and configured from there.
  HOWSO_JOB_RUNNER_POD_ANNOTATIONS: {{ .Values.jobRunner.podAnnotations | toJson | quote }}
  HOWSO_JOB_RUNNER_TOLERATIONS: {{ .Values.tolerations.workers | toJson | quote }}
  HOWSO_JOB_RUNNER_POD_SECURITY_CONTEXT: {{ .Values.jobRunner.podSecurityContext | toJson | quote }}
  HOWSO_JOB_RUNNER_SECURITY_CONTEXT: {{ .Values.jobRunner.securityContext | toJson | quote }}

