{{- if not (.Values.datastores.objectStore.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: platform-object-store-credentials
  labels:
    app.kubernetes.io/part-of: howso-platform
    app.kubernetes.io/component: platform-object-store
type: Opaque
data:
  accesskey: "{{ .Values.datastores.objectStore.accesskey | b64enc }}"
  secretkey: "{{ .Values.datastores.objectStore.secretkey | b64enc }}"
{{- end }}