{{ if .Values.docs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: platform-docs-application-secret
type: Opaque
data:
  client_id: {{ "platform-docs-app-client-id" | b64enc | quote }} 
  client_secret: {{ randAlphaNum 130 | b64enc }} # Randomly generated secret 
  cookie_secret: {{ randAlphaNum 32 | b64enc }} # cookie_secret must be 16, 24, or 32 bytes to create an AES cipher 
{{- end }}