{{- if .Values.docs.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
  {{ if .Values.podTLS.enabled }}
    projectcontour.io/upstream-protocol.tls: 8443,https  # https://projectcontour.io/docs/main/config/upstream-tls/
  {{ end }}
  name: {{ include "howso-platform.docs.fullname" . }}
  labels:
    {{- include "howso-platform.docs.labels" . | nindent 4 }}
spec:
  type: ClusterIP 
  ports:
    {{ if .Values.podTLS.enabled }}
    - port: 8443 
      targetPort: https
      protocol: TCP
      name: https
    {{ else }}
    - port: 4180 
      targetPort: 4180 
      protocol: TCP
      name: http
    {{ end }}
  selector:
    {{- include "howso-platform.docs.selectorLabels" . | nindent 4 }}
{{- end }}