apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-cert-generator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: platform-secret-manager-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-secret-manager-binding
subjects:
- kind: ServiceAccount
  name: platform-cert-generator-sa
roleRef:
  kind: Role
  name: platform-secret-manager-role
  apiGroup: rbac.authorization.k8s.io
