{{- if not (.Values.datastores.redis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: platform-redis-credentials
  labels:
    app: redis 
type: Opaque
data:
  password: "{{ .Values.datastores.redis.password | b64enc }}"
{{- end }}